name = "hono"
main= "src/index.ts"
compatibility_date = "2025-04-11"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "dishcode"
database_id = "3661ea71-7787-48ec-a54b-9cb349a04eac"

[vars]
EXTERNAL_API_URL = "https://browser-use-dishcode-backend-api-production.up.railway.app/api/search-agent-super-cool"
NEXT_PUBLIC_API_BASE_URL="https://hono.daigaku-150207.workers.dev"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_cmlnaHQtbWFzdG9kb24tNzQuY2xlcmsuYWNjb3VudHMuZGV2JA"
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
CLERK_JWT_PUBLIC_KEY = """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvT9VzVm1HCDwDndahK4Y
wQy9QbQrXAy6KDAuaH6lZbNcoKV9Iy1VUeJNg2NkS/BXzcGfi77tDJ+RwGSIRzGX
Ps3oW6/+EyZ5pw1wI0nY3A88dUUjqWeyq+kzJpboff2f4Wf8xFsHOmcjF4o94HMr
uErv2y6E/bHfYSAjSOtSQ+zwcesETndQea1GZqfhS+kfmD/F7DMiKO3ie7iV4Bu/
TCqNXC5FfK6hZFvAIip1DXXihBr6ebnJSURrzETwx97CJ+qjJ6qBzk0axzrHGkF0
LuzFmjq9eg9u21mxy9rRVitC3tPUpsU8Zdgo7KkgkPUFNZLPNspDOMONyQqtDI72
LQIDAQAB
-----END PUBLIC KEY-----
"""
