name = "dishcode"

compatibility_date = "2024-10-18"
compatibility_flags = ["nodejs_compat"]  # node:buffer, node:async_hooks を使うのに必要

# Pages 用の設定 (必須)
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_cmlnaHQtbWFzdG9kb24tNzQuY2xlcmsuYWNjb3VudHMuZGV2JA"
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
NEXT_PUBLIC_CLERK_FRONTEND_API = "clerk.dishcode-988456740216.clerk.accounts.dev"